### ISSUE TITLE
Logic App: Event Hub-trigger creation process has changed

### ISSUE THREAD

**Issue by teodoran** [cx-cloud-101/speedtest-workshop#5]
Documentation and images is outdated and causes confusion. This should be updated according to the new flow. Affects [Scheduling Speed Tests](https://cx-cloud-101.github.io/speedtest-workshop/azure/scheduling-speedtests) and [The one with the Web Page](https://cx-cloud-101.github.io/speedtest-workshop/azure/the-web-page)

**Comment by gcp-testbruker** [comment]
Fixed in last version
