### ISSUE TITLE
Section Publishing TestResults to Event Hub: Better description of code changes

### ISSUE THREAD

**Issue by teodoran** [cx-cloud-101/speedtest-workshop#6]
This relates to the "Publishing TestResults to Event Hub"-section at [Events! Events! Events!](https://cx-cloud-101.github.io/speedtest-workshop/azure/events-events).

A lot of code manipulation is needed in this section, and some participants found it a bit confusing. One suggestion was to point out what files need to be updated, and another was to give a link to en example of the final code at the end of the section.

**Comment by gcp-testbruker** [comment]
This seems to work fine in the latest version.
